import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profielPic from "../../public/images/profile/developer-pic-1.png";
import lightBulib from "../../public/images/svgs/miscellaneous_icons_1.svg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";
import HierMe from "@/components/HierMe";
import TransitionEffect from "./../components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mohamed Baghough Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout className="pt-0 md:pt-16 ">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profielPic}
                alt="Mohamed Baghough"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw,
                (max-width:1200px) 50vw,
                50vw
                "
              />
            </div>
            <div className="flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design"
                className="!text-left !text-7xl xl:!text-5xl lg:!text-6xl md:!text-5xl sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  download={true}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark  dark:bg-light dark:text-dark dark:hover:bg-dark hover:dark:border-light dark:hover:text-light    
                  md:p-2 md:px-4 md:text-base"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:simozrt7@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium underline capitalize text-dark dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HierMe />
        <div className="absolute inline-block w-20 right-8 bottom-8 ">
          <Image
            src={lightBulib}
            alt="Mohamed Baghoug"
            className="w-full h-auto md:hidden"
          />
        </div>
      </main>
    </>
  );
}
